include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Effective Dart style rules
    prefer_single_quotes: true
    prefer_final_locals: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    avoid_print: true

    # Documentation rules
    public_member_api_docs: false  # Enable later when APIs stabilize
